'use client'

import { useState, useEffect, Suspense } from 'react'
import { useRouter, useSearchParams } from 'next/navigation'

// ============================================================
// Screen 7: Updated Recommendations
// Shows re-generated learning path + updated mastery after quiz
// Per PROJECT_SPEC.md §9 and IMPLEMENTATION_PLAN.md Phase 8
// ============================================================

interface PathItem {
  id?: string
  conceptId: string
  conceptName: string
  topicName?: string
  orderIndex: number
  reason: string
  masteryPercent: number
  status: 'STRONG' | 'DEVELOPING' | 'GAP'
  lastScorePercent?: number | null
  prerequisiteBlocked?: boolean
}

interface Student {
  id: string
  name: string
}

const STATUS_CONFIG = {
  STRONG:     { label: 'Strong',     color: 'text-success-400', bg: 'bg-success-500/10 border-success-500/30', badge: 'badge-strong' },
  DEVELOPING: { label: 'Developing', color: 'text-warning-400', bg: 'bg-warning-500/10 border-warning-500/30', badge: 'badge-developing' },
  GAP:        { label: 'Gap',        color: 'text-danger-400',  bg: 'bg-danger-500/10  border-danger-500/30',  badge: 'badge-gap' },
}

function MasteryBar({ percent, status }: { percent: number; status: string }) {
  const barColor =
    status === 'STRONG' ? 'bg-success-500' :
    status === 'DEVELOPING' ? 'bg-warning-500' : 'bg-danger-500'
  return (
    <div className="mastery-bar mt-1">
      <div
        className={`mastery-bar-fill ${barColor} transition-all duration-700`}
        style={{ width: `${Math.min(100, Math.max(0, percent))}%` }}
      />
    </div>
  )
}

function RecommendationsContent() {
  const router = useRouter()
  const searchParams = useSearchParams()
  const studentId = searchParams.get('studentId')
  const subjectId = searchParams.get('subjectId')

  const [student, setStudent] = useState<Student | null>(null)
  const [pathItems, setPathItems] = useState<PathItem[]>([])
  const [overallMastery, setOverallMastery] = useState<number>(0)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')

  useEffect(() => {
    if (!studentId) { router.push('/'); return }
    loadData()
  }, [studentId, subjectId])

  async function loadData() {
    setLoading(true)
    setError('')
    try {
      // Load current path (already regenerated by quiz/complete)
      const pathUrl = subjectId
        ? `/api/path?studentId=${studentId}&subjectId=${subjectId}`
        : `/api/path?studentId=${studentId}`
      const analysisUrl = subjectId
        ? `/api/analysis?studentId=${studentId}&subjectId=${subjectId}`
        : `/api/analysis?studentId=${studentId}`

      const [pathRes, analysisRes] = await Promise.all([
        fetch(pathUrl),
        fetch(analysisUrl),
      ])

      const pathData = await pathRes.json()
      const analysisData = await analysisRes.json()

      if (pathData.error) { setError(pathData.error); return }
      if (analysisData.error) { setError(analysisData.error); return }

      setStudent(pathData.student ?? analysisData.student)
      setPathItems(pathData.items ?? [])
      setOverallMastery(analysisData.overallMastery ?? 0)
    } catch {
      setError('Failed to load recommendations')
    } finally {
      setLoading(false)
    }
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="text-center">
          <div className="animate-pulse-soft text-5xl mb-4">🗺️</div>
          <p className="text-[#8b95a8]">Loading updated recommendations...</p>
        </div>
      </div>
    )
  }

  if (error) {
    return (
      <div className="page-content flex items-center justify-center">
        <div className="card max-w-md text-center">
          <div className="text-4xl mb-4">⚠️</div>
          <p className="text-danger-400 mb-4">{error}</p>
          <button onClick={() => router.push(`/path?studentId=${studentId}${subjectId ? `&subjectId=${subjectId}` : ''}`)} className="btn-secondary">
            ← Back to Path
          </button>
        </div>
      </div>
    )
  }

  const gaps = pathItems.filter(i => i.status === 'GAP')
  const developing = pathItems.filter(i => i.status === 'DEVELOPING')
  const strong = pathItems.filter(i => i.status === 'STRONG')

  const overallStatus =
    overallMastery >= 70 ? 'STRONG' :
    overallMastery >= 40 ? 'DEVELOPING' : 'GAP'

  return (
    <div className="page-container">
      {/* Header */}
      <div className="page-header">
        <div className="max-w-4xl mx-auto">
          <div className="flex items-center justify-between mb-1">
            <div>
              <div className="text-xs text-[#5a6478] uppercase tracking-wider mb-0.5">Updated Recommendations</div>
              <h1 className="font-bold text-[#e8eaf0]">
                {student?.name ?? 'Student'} — Current Learning Path
              </h1>
            </div>
            <div className="text-right">
              <div className="text-xs text-[#5a6478] mb-0.5">Overall Mastery</div>
              <div className={`text-2xl font-extrabold ${STATUS_CONFIG[overallStatus].color}`}>
                {overallMastery.toFixed(0)}%
              </div>
            </div>
          </div>
          <MasteryBar percent={overallMastery} status={overallStatus} />
        </div>
      </div>

      <div className="page-content">
        {/* Summary cards */}
        <div className="grid grid-cols-3 gap-4 mb-8">
          <div className="card text-center">
            <div className="text-3xl font-bold text-danger-400">{gaps.length}</div>
            <div className="text-xs text-[#5a6478] mt-1">Knowledge Gaps</div>
          </div>
          <div className="card text-center">
            <div className="text-3xl font-bold text-warning-400">{developing.length}</div>
            <div className="text-xs text-[#5a6478] mt-1">Developing</div>
          </div>
          <div className="card text-center">
            <div className="text-3xl font-bold text-success-400">{strong.length}</div>
            <div className="text-xs text-[#5a6478] mt-1">Strong</div>
          </div>
        </div>

        {/* Learning Path (ordered) */}
        <div className="mb-8">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-base font-bold text-[#e8eaf0]">
              Priority Learning Path
              <span className="ml-2 text-xs text-brand-400 font-normal">(Updated after last quiz)</span>
            </h2>
            <span className="text-xs text-[#5a6478]">{pathItems.length} concepts</span>
          </div>

          {pathItems.length === 0 ? (
            <div className="card text-center text-[#5a6478] text-sm">
              No path data found. Return to Learning Path to regenerate.
            </div>
          ) : (
            <div className="space-y-3">
              {pathItems.map((item, idx) => {
                const cfg = STATUS_CONFIG[item.status]
                return (
                  <div
                    key={item.conceptId}
                    className={`card border ${cfg.bg} animate-slide-up`}
                    style={{ animationDelay: `${idx * 60}ms` }}
                  >
                    <div className="flex items-start justify-between gap-4">
                      <div className="flex items-center gap-3 min-w-0">
                        {/* Priority number */}
                        <div className={`w-7 h-7 rounded-full flex items-center justify-center text-xs font-bold flex-shrink-0 border ${
                          item.status === 'GAP' ? 'bg-danger-500/20 border-danger-500/40 text-danger-300' :
                          item.status === 'DEVELOPING' ? 'bg-warning-500/20 border-warning-500/40 text-warning-300' :
                          'bg-success-500/20 border-success-500/40 text-success-300'
                        }`}>
                          {idx + 1}
                        </div>
                        <div className="min-w-0">
                          <div className="font-semibold text-[#e8eaf0] text-sm">{item.conceptName}</div>
                          <div className="text-xs text-[#5a6478] mt-0.5 truncate">{item.reason}</div>
                        </div>
                      </div>

                      <div className="flex items-center gap-3 flex-shrink-0">
                        <div className="text-right">
                          <div className={`font-bold text-sm ${cfg.color}`}>
                            {item.masteryPercent.toFixed(0)}%
                          </div>
                          <div className="w-20">
                            <MasteryBar percent={item.masteryPercent} status={item.status} />
                          </div>
                        </div>
                        <span className={cfg.badge}>{cfg.label}</span>
                      </div>
                    </div>

                    {/* Quiz this concept */}
                    <div className="mt-3 pt-3 border-t border-[#2a3347] flex gap-2">
                      <button
                        id={`rec-quiz-${item.conceptId}`}
                        onClick={() => router.push(`/quiz?studentId=${studentId}&conceptId=${item.conceptId}${subjectId ? `&subjectId=${subjectId}` : ''}`)}
                        className="btn-primary text-xs py-1.5 px-3"
                      >
                        Take Quiz →
                      </button>
                      <button
                        id={`rec-learn-${item.conceptId}`}
                        onClick={() => router.push(`/learn?studentId=${studentId}&conceptId=${item.conceptId}${subjectId ? `&subjectId=${subjectId}` : ''}`)}
                        className="btn-secondary text-xs py-1.5 px-3"
                      >
                        Study with AI
                      </button>
                    </div>
                  </div>
                )
              })}
            </div>
          )}
        </div>

        {/* Navigation */}
        <div className="flex flex-wrap gap-3 justify-center">
          <button
            id="rec-back-path-btn"
            onClick={() => router.push(`/path?studentId=${studentId}${subjectId ? `&subjectId=${subjectId}` : ''}`)}
            className="btn-secondary"
          >
            ← Learning Path
          </button>
          <button
            id="rec-new-diagnostic-btn"
            onClick={() => router.push(`/diagnostic?studentId=${studentId}${subjectId ? `&subjectId=${subjectId}` : ''}`)}
            className="btn-primary"
          >
            Retake Diagnostic →
          </button>
          <button
            id="rec-home-btn"
            onClick={() => router.push('/')}
            className="btn-secondary"
          >
            🏠 Home
          </button>
        </div>
      </div>
    </div>
  )
}

export default function RecommendationsPage() {
  return (
    <Suspense fallback={<div className="flex items-center justify-center min-h-screen text-[#8b95a8]">Loading...</div>}>
      <RecommendationsContent />
    </Suspense>
  )
}
